development:
  adapter: mysql2
  database: sauron_test_app_dev
  encoding: utf8
  username: root
  host: localhost
  encoding: utf8mb4
  collation: utf8mb4_bin

production:
  adapter: mysql2
  database: sauron_test_app_prod
  encoding: utf8
  username: root
  password: saurontest
  host: sauron-test-app-prod.c283n6dl28pf.ap-northeast-1.rds.amazonaws.com
  encoding: utf8mb4
  collation: utf8mb4_bin
